version: "3.3"
services:
  web:
    image: mikehearn/shlearn-wedding-backend:latest
    networks:
      - traefik_public
      - db_overlay
    env_file: .env
    command: >
      /bin/bash -c
      "pipenv run uwsgi
      --http :8000
      --chdir $$(pwd)/rsvp_backend
      --module rsvp_backend.wsgi
      --env DJANGO_SETTINGS_MODULE=$$DJANGO_SETTINGS_MODULE
      --virtualenv $$(pipenv --venv)"
    deploy:
      replicas: 1
      labels:
        - "traefik.backend=httpbackend"
        - "traefik.port=8000"
        - "traefik.frontend.rule=PathPrefix:/api,/admin"
        - "traefik.docker.network=traefik_public"
  db:
    image: postgres
    env_file: .env
    volumes:
      - type: bind
        source: ./db
        target: /var/lib/postgresql/data
    networks:
      - db_overlay
    deploy:
      replicas: 1

networks:
  traefik_public:
    external: true
  db_overlay:
    driver: overlay
