# Generated by Django 2.0.3 on 2018-03-16 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='additional_notes',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='music_suggestions',
            field=models.CharField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='person',
            name='attendance',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='food_choice',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='full_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='internal_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='rsvp.Invitation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='nickname',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
