# Generated by Django 2.0.3 on 2018-03-16 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0002_auto_20180316_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='additional_notes',
            field=models.TextField(blank=True, max_length=1000),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='music_suggestions',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
