# Generated by Django 2.0.3 on 2018-03-16 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0003_auto_20180316_1632'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='person',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='person',
            name='nickname',
        ),
        migrations.AddField(
            model_name='person',
            name='first_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='person',
            name='last_name',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
