# Generated by Django 2.0.3 on 2018-03-23 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rsvp', '0006_auto_20180316_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='is_plus_one',
            field=models.BooleanField(default=False),
        ),
    ]
